# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        buildozer_version: stable
    - name: create apk
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install buildozer
        pip install cython==0.29.19
        sudo apt-get install -y \python3-pip \build-essential \git \python3 \python3-dev \ffmpeg \libsdl2-dev \libsdl2-image-dev \libsdl2-mixer-dev \libsdl2-ttf-dev \libportmidi-dev \libswscale-dev \libavformat-dev \libavcodec-dev \zlib1g-dev
        sudo apt-get install -y \libgstreamer1.0 \gstreamer1.0-plugins-base \gstreamer1.0-plugins-good
        sudo apt-get install build-essential libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev libffi-dev uuid-dev libffi6
        sudo apt-get install libffi-dev
        buildozer -v android debug 
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install buildozer
        pip install cython==0.29.19
        sudo apt-get install -y \python3-pip \build-essential \git \python3 \python3-dev \ffmpeg \libsdl2-dev \libsdl2-image-dev \libsdl2-mixer-dev \libsdl2-ttf-dev \libportmidi-dev \libswscale-dev \libavformat-dev \libavcodec-dev \zlib1g-dev
        sudo apt-get install -y \libgstreamer1.0 \gstreamer1.0-plugins-base \gstreamer1.0-plugins-good
        sudo apt-get install build-essential libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev libffi-dev uuid-dev libffi6
        sudo apt-get install libffi-dev
        buildozer -v android debug 
        twine upload dist/*
